"""add preprocessing tables

Revision ID: faf53dcd4e83
Revises: b56124af2629
Create Date: 2026-07-28 17:45:04.095552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf53dcd4e83'
down_revision: Union[str, Sequence[str], None] = 'b56124af2629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column("emails", sa.Column("is_chunked", sa.Boolean(), nullable=False, server_default=sa.false(),),)
    op.alter_column("emails", "is_chunked", server_default=None,)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'is_chunked')
    op.drop_table('email_chunks')
    # ### end Alembic commands ###
