from src.embeddings import EmbeddingService


def main():

    embedding_service = EmbeddingService()

    text = """
    Hello!
    This is my first embedding generated by QueryMind.
    """

    embedding = embedding_service.embed(text)

    print(f"Embedding length : {len(embedding)}")

    print()

    print("First 10 values:")

    print(embedding[:10])


if __name__ == "__main__":
    main()